[book]
title = "我的评测工具链"
authors = ["BiBoyang"]
language = "zh-CN"
src = "src"

[build]
build-dir = "../../books/eval-series"
create-missing = false

[output.html]
no-section-label = true
git-repository-url = "https://github.com/BiBoyang/BiBoyang.github.io"
